### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by suichanwa** [LJB018/Gentoo-Simple-Installer#3]
So, when i got to this point of install

"Enter the drive you want to install Gentoo onto: (This will destroy all data on your drive!)" TARGET_DISK

i get this issue 

https://anonfiles.com/DcDbz4J1u5/photo_2021-09-24_12-32-46_jpg
https://imgur.com/a/HmBrYJQ
what i need to write to this script take my value?

**Comment by LJB018** [comment]
The issue was that I wasn't suppose to add "esac" to this script. 

I have fixed this bug now; you can run this script without any errors.
